### ISSUE TITLE
Suggestion of another recipe

### ISSUE THREAD

**Issue by chrlundtoft** [matthew-morris-cessda/forking-workflow-exercise#2]
Another suggestion for a recipe

**Comment by matthew-morris-cessda** [comment]
Could you elaborate on what this recipe would be?

**Comment by chrlundtoft** [comment]
Found some suggestions here: https://www.delish.com/cooking/recipe-ideas/g2786/easy-taco-recipes/

**Comment by matthew-morris-cessda** [comment]
Okay, I think this would be a valuable contribution.
